# Generated by Django 4.0.2 on 2023-08-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationuser_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='project',
        ),
    ]
