# Generated by Django 4.0.2 on 2023-08-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationuser_level_notificationuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='hierarchy_type',
        ),
    ]
