# Generated by Django 4.0.2 on 2023-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_notificationuser_hierarchy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='hierarchy_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'initiator'), (2, 'Recommender'), (3, 'Approver')], null=True),
        ),
    ]
