# Generated by Django 4.0.2 on 2023-08-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notificationuser_hierarchy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationuser',
            name='user',
        ),
    ]
