# Generated by Django 4.0.2 on 2023-09-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_equipment_equipment_ship_id'),
        ('notification', '0009_notificationuser_from_user_notificationuser_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.project'),
        ),
    ]
