# Generated by Django 4.0.2 on 2023-07-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logon_type', models.CharField(max_length=150)),
                ('log_datetime', models.DateTimeField(auto_now_add=True)),
                ('log_ip', models.GenericIPAddressField()),
                ('log_browser', models.CharField(blank=True, max_length=100, null=True)),
                ('log_version', models.CharField(blank=True, max_length=100, null=True)),
                ('log_os', models.CharField(blank=True, max_length=100, null=True)),
                ('log_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login',
                'verbose_name_plural': 'User Login',
                'db_table': 'log.user_login',
            },
        ),
    ]
