# Generated by Django 4.0.2 on 2023-07-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsmapping',
            name='order',
        ),
    ]
