# Generated by Django 4.0.2 on 2023-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_formsmapping_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsmapping',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
