# Generated by Django 4.0.2 on 2023-07-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_formsmapping_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltransactiondetails',
            name='para_no',
        ),
        migrations.RemoveField(
            model_name='globaltransactiondetailslog',
            name='para_no',
        ),
    ]
