# Generated by Django 4.0.2 on 2023-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_globaltransactiondetails_para_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltransactiondetails',
            name='para_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='globaltransactiondetailslog',
            name='para_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
