# Generated by Django 4.0.2 on 2023-07-28 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
        ('transaction', '0006_formlevelhierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLevelHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_level', models.IntegerField(null=True)),
                ('approver_level', models.IntegerField(null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Delete')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField()),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_level_approver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.forms')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.project')),
                ('recommender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_level_recommender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hierarchy_project_level',
                'verbose_name_plural': 'hierarchy_project_level',
                'db_table': 'hierarchy.project_level',
            },
        ),
    ]
