# Generated by Django 4.0.2 on 2023-07-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_projectlevelhierarchy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormLevelHierarchy',
        ),
    ]
