# Generated by Django 4.0.2 on 2023-07-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_projectlevelrecommenderhierarchy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectLevelHierarchy',
        ),
    ]
