# Generated by Django 4.0.2 on 2023-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_globaltransaction_approver_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlevelrecommenderhierarchy',
            name='recommender_level_status',
            field=models.SmallIntegerField(choices=[(1, 'accept'), (2, 'reject')], null=True),
        ),
    ]
