# Generated by Django 4.0.2 on 2023-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_alter_formlevelrecommenderhierarchy_recommender_level_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlevelrecommenderhierarchy',
            name='recommender_level_status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
