# Generated by Django 4.0.2 on 2023-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_projectlevelrecommenderhierarchy_recommender_level_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlevelapproverhierarchy',
            name='approver_level_status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
