# Generated by Django 4.0.2 on 2023-08-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0023_formlevelapproverhierarchy_approver_level_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlevelrecommenderhierarchy',
            name='current_reject_level',
            field=models.SmallIntegerField(null=True),
        ),
    ]
