# Generated by Django 4.0.2 on 2023-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0025_remove_formlevelrecommenderhierarchy_current_reject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlevelrecommenderhierarchy',
            name='current_reject',
            field=models.SmallIntegerField(null=True),
        ),
    ]
