# Generated by Django 4.0.2 on 2023-08-23 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_equipment_equipment_ship_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0026_formlevelrecommenderhierarchy_current_reject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTransactionShipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=15)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Delete')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField()),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.command')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.forms')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.project')),
            ],
            options={
                'verbose_name': 'transaction_ship_details',
                'verbose_name_plural': 'transaction_ship_details',
                'db_table': 'transaction.ship_details',
            },
        ),
    ]
