# Generated by Django 4.0.2 on 2023-08-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0027_globaltransactionshipdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltransactionshipdetail',
            name='ship_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
