# Generated by Django 4.0.2 on 2023-08-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0029_remove_globaltransactionshipdetail_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltransactionapproval',
            name='type',
        ),
    ]
