# Generated by Django 4.0.2 on 2023-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0030_remove_globaltransactionapproval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltransactionapproval',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'initiator'), (2, 'Recommendation'), (3, 'Approval')], null=True),
        ),
    ]
