# Generated by Django 4.0.2 on 2023-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0031_globaltransactionapproval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlevelrecommenderhierarchy',
            name='current_reject',
            field=models.SmallIntegerField(null=True),
        ),
    ]
