# Generated by Django 4.0.2 on 2023-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0032_projectlevelrecommenderhierarchy_current_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlevelapproverhierarchy',
            name='approver_level_status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
