# Generated by Django 4.0.2 on 2023-09-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_equipment_equipment_ship_id'),
        ('transaction', '0033_projectlevelapproverhierarchy_approver_level_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlevelapproverhierarchy',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.project'),
        ),
        migrations.AddField(
            model_name='formlevelrecommenderhierarchy',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.project'),
        ),
    ]
