# Generated by Django 4.0.2 on 2023-09-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0034_formlevelapproverhierarchy_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlevelapproverhierarchy',
            name='project',
        ),
        migrations.RemoveField(
            model_name='formlevelrecommenderhierarchy',
            name='project',
        ),
    ]
