# Generated by Django 4.0.2 on 2023-07-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_initial'),
        ('master', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.unit'),
        ),
        migrations.AddField(
            model_name='user',
            name='process',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.process'),
        ),
    ]
