# Generated by Django 4.0.2 on 2023-08-15 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Delete')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField()),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.project')),
            ],
            options={
                'verbose_name': 'ships',
                'verbose_name_plural': 'ships',
                'db_table': 'master.ships',
            },
        ),
    ]
