# Generated by Django 4.0.2 on 2023-08-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_ships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ships',
        ),
    ]
